name = "ui"
version = "1.0.0"
description = "Lustre SPA for pie-safe"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
core = { path = "../core" }
lustre = ">= 5.6.0 and < 6.0.0"
modem = ">= 2.1.0 and < 3.0.0"
lustre_http = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[lustre.build]
outdir = "../backend/priv/static"

[lustre.dev]
proxy = { from = "/", to = "http://localhost:3000" }
